<?php

/* * *************************************************************
 * Extension Manager/Repository config file for ext: "vmfds_sermons"
 *
 * Auto generated by Extension Builder 2013-04-16
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 * ************************************************************* */

$EM_CONF[$_EXTKEY] = array(
    'title' => 'Sermons',
    'description' => '',
    'category' => 'plugin',
    'author' => 'Christoph Fischer',
    'author_email' => 'christoph.fischer@volksmission.de',
    'author_company' => 'Volksmission Freudenstadt',
    'shy' => '',
    'priority' => '',
    'module' => '',
    'state' => 'stable',
    'internal' => '',
    'uploadfolder' => '1',
    'createDirs' => '',
    'modify_tables' => '',
    'clearCacheOnLoad' => 0,
    'lockType' => '',
    'version' => '1.1',
    'constraints' => array(
        'depends' => array(
            'extbase' => 'undefined',
            'fluid' => 'undefined',
            'typo3' => '6.0',
        ),
        'conflicts' => array(
        ),
        'suggests' => array(
        ),
    ),
);
?>